sonar.projectKey=oficina_mecanica
sonar.projectName=Oficina Mecanica API
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=spec

sonar.exclusions=\
  app/assets/**,\
  app/views/**,\
  vendor/**,\
  db/schema.rb,\
  db/migrate/**,\
  public/**,\
  node_modules/**,\
  log/**,\
  tmp/**,\
  storage/**,\
  coverage/**

sonar.test.exclusions=\
  spec/swagger_helper.rb,\
  spec/support/**

sonar.language=ruby
sonar.sourceEncoding=UTF-8

sonar.ruby.coverage.reportPaths=coverage/coverage.json

sonar.host.url=http://sonarqube:9000
