apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secrets
  namespace: default
type: Opaque
data:
  OFICINA_MECANICA_DATABASE_PASSWORD: "DATABASE_PASSWORD_PLACEHOLDER"
  SECRET_KEY_BASE: "SECRET_KEY_BASE_PLACEHOLDER"
