apiVersion: v1
kind: Service
metadata:
  name: oficina-mecanica-web-service
  namespace: default
  labels:
    app: oficina-mecanica-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: oficina-mecanica-web
